# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

appName = "HowMuch"
changelog = %q( Ускорена загрузка приложения.
Устранены лаги при перехода с экрана на экран.  
)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do    
    increment_version  
    build_app(
      workspace: "#{appName}.xcworkspace",
      scheme: appName,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.maxkazakov.Howmuch" => "howMuch"          
        }      
      }      
    )  

    upload
  end

  lane :increment_version do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "#{appName}.xcodeproj"
    )
  end

  lane :upload do 
    upload_to_testflight(
      distribute_external: true,
      changelog: changelog,
      beta_app_description: "Привет ребята, я просто пока что тестирую скрипты",
      groups: ["Друзья"]
    )
  end
end


