# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

appName = "HowMuch"

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do    
    increment_version  
    build_app(
      workspace: "#{appName}.xcworkspace",
      scheme: appName,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.maxkazakov.Howmuch" => "howMuch"          
        }
      }
    )    
    upload_to_testflight
  end

  lane :increment_version do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "#{appName}.xcodeproj"
    )
  end
end


